### ISSUE TITLE
Need new WS1 Access Logo

### ISSUE THREAD

**Issue by helmlingp** [euc-dev/euc-dev.github.io#1]
Need new WS1 Access Logo

**Comment by parrybarwick** [comment]
An icon that works on both white and black backgrounds please.

**Comment by anoopgarlapati** [comment]
I have svg logo of Workspace ONE Access with me (with and without product names and in 16 px and 400 px) which I downloaded from brand portal when it was still accessible. Would that work for both light and dark modes?

**Comment by helmlingp** [comment]
thanks @anoopgarlapati I have updated using the same ones from brand portal (I too had grabbed them ;) )

branding is a secondary effort here, we really just want to get the portal into a place that we can manage easily moving forward.
