### ISSUE TITLE
add Workspace ONE Access API info

### ISSUE THREAD

**Issue by helmlingp** [euc-dev/euc-dev.github.io#3]
add the following to the APIs page:
https://techzone.omnissa.com/resource/getting-started-workspace-one-uem-api-postman-collection

may need to create a new github repo

**Comment by anoopgarlapati** [comment]
@helmlingp I recently updated Workspace ONE Access API in the current version of Omnissa developer portal. The API and swagger doc are available at https://developer.omnissa.com/ws1-dev-centre/apis/workspace-one-access/ 
Please let me know if anything more is needed from Workspace ONE Access team.
