### ISSUE TITLE
Workspace ONE Access API page does not load properly

### ISSUE THREAD

**Issue by anoopgarlapati** [euc-dev/euc-dev.github.io#8]
Navigating to Workspace ONE Access APIs page does not load properly at first: 
<img width="1725" alt="image" src="https://github.com/user-attachments/assets/0e3668a9-45fb-46ca-8a3f-61b7f8801220">

Upon reloading the page, it loads another version of page which is incorrect as well, this contains references to EUC Samples:
<img width="1722" alt="image" src="https://github.com/user-attachments/assets/5196e4c7-5dc8-47f7-ab9d-fdae755b2a61">

**Comment by helmlingp** [comment]
Issue with swagger file. Obtained and deployed openapi json version.
